/* Automatic generated by './build/bin/build-entry.js' */

import grid from '../packages/grid.vue';
import queryForm from '../packages/queryForm.vue';

const install = function(Vue, opts = {}) {
    /* istanbul ignore if */
    if (install.installed) return;
    Vue.component(grid.name, grid);
    Vue.component(queryForm.name, queryForm);
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
};

module.exports = {
    version: '1.0.9',
    grid,
    queryForm
};
